version: '3.8'

services:
  bh:
    build:
      context: .
      dockerfile: Dockerfile.BH
    ports:
      - "9090:9090"
    container_name: bh_service

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.Orch
    ports:
      - "8080:8080"
    container_name: orchestrator_service

  demon:
    build:
      context: .
      dockerfile: Dockerfile.Demon
    ports:
      - "8081:8081"
    container_name: demon_service